// GENERATED by tools/gen_page.mjs from setup.html - do not edit.
using UnityEngine.UIElements;

namespace LolHost
{
    public static class SetupMarkup
    {
        /// <summary>setup.html's &lt;body&gt;, built under root (ids: setup-&lt;id&gt;).</summary>
        public static void Build(VisualElement root)
        {
            var e0 = Dom.El("main", "setup", null, false);
            root.Add(e0);
            var e1 = Dom.El("h1", "", "Game data", false);
            e0.Add(e1);
            var e2 = Dom.El("p", "", null, true);
            e0.Add(e2);
            e2.Append("This app does not include the game. Point it at your GOG ");
            var e3 = Dom.El("em", "", "Lands of Lore: The Throne of Chaos", false);
            e2.Add(e3);
            e2.Append(" installation (the folder with ");
            var e4 = Dom.El("code", "", "GAME.DAT", false);
            e2.Add(e4);
            e2.Append(", usually ");
            var e5 = Dom.El("code", "", "C:\\GOG Games\\Lands Of Lore", false);
            e2.Add(e5);
            e2.Append(") and it will import the files once into ");
            var e6 = Dom.El("code", "", "its data folder", false);
            Dom.Register("setup-target", e6);
            e2.Add(e6);
            e2.Append(".");
            var e7 = Dom.El("p", "", null, true);
            e0.Add(e7);
            var e8 = Dom.El("button", "", "Choose the GOG folder…", false);
            Dom.Register("setup-pick", e8);
            e8.SetAttr("type", "button");
            e7.Add(e8);
            var e9 = Dom.El("div", "bar", null, false);
            e9.SetAttr("hidden", "");
            e0.Add(e9);
            var e10 = Dom.El("i", "", null, false);
            Dom.Register("setup-fill", e10);
            e9.Add(e10);
            var e11 = Dom.El("p", "", null, false);
            Dom.Register("setup-status", e11);
            e0.Add(e11);
        }
    }
}
