// Cross-module index for the transliteration: every method (async or not, parameters) and every
// `this.x =` field of src/game + src/formats, with the module that owns it. Output: docs/port/index.md
import fs from "fs";
import path from "path";
const LANDS = process.argv[2] || (process.env.LANDS || (process.env.HOME || "") + "/lands");
const files = [...fs.readdirSync(path.join(LANDS, "src/game")).map((f) => `game/${f}`), ...fs.readdirSync(path.join(LANDS, "src/formats")).map((f) => `formats/${f}`)].filter((f) => f.endsWith(".mjs"));
const methods = []; const fields = new Map();
for (const file of files) {
  const src = fs.readFileSync(path.join(LANDS, "src", file), "utf8");
  const lines = src.split("\n");
  let inInit = null;
  lines.forEach((line, n) => {
    const m = line.match(/^  (async )?(?:static )?([A-Za-z_]\w*)\s*\(([^)]*)\)\s*\{/);
    if (m && !["if", "for", "while", "switch", "catch", "function"].includes(m[2])) { methods.push({ file, name: m[2], async: !!m[1], params: m[3].trim(), line: n + 1 }); inInit = /^init|constructor/.test(m[2]) ? m[2] : null; }
    const f = /^export (async )?function (\w+)\(([^)]*)\)/.exec(line);
    if (f) methods.push({ file, name: f[2], async: !!f[1], params: f[3], line: n + 1, exported: true });
    for (const a of line.matchAll(/this\.([A-Za-z_]\w*)\s*=(?!=)\s*([^;]*)/g)) {
      const [ , name, value ] = a;
      const prev = fields.get(name);
      const score = inInit ? 2 : 1;
      if (!prev || score > prev.score) fields.set(name, { file, value: value.trim().slice(0, 70), score, where: inInit || `line ${n + 1}` });
    }
  });
}
let out = "# Cross-module index (generated by tools/gen_index.mjs)\n\n## Methods: module, name(params), async\n\n";
for (const m of methods) out += `- ${m.file}:${m.line} ${m.async ? "**async** " : ""}${m.exported ? "export " : ""}\`${m.name}(${m.params})\`\n`;
out += "\n## Fields: `this.x =` owner module (init method if any), first/initial value\n\n";
for (const [name, f] of [...fields].sort()) out += `- \`${name}\` — ${f.file} (${f.where}): \`${f.value}\`\n`;
fs.writeFileSync(new URL("../docs/port/index.md", import.meta.url), out);
console.log(`${methods.length} methods (${methods.filter((m) => m.async).length} async), ${fields.size} fields`);
