// Generates Engine/Static/StaticData.g.cs from the browser build's src/game/static-data.mjs, so the
// C# engine reads exactly the same tables. Re-run whenever static-data.mjs changes.
//   node tools/gen_static.mjs [LANDS dir]
import fs from "fs";
import path from "path";

const LANDS = process.argv[2] || process.env.LANDS || (process.env.LANDS || (process.env.HOME || "") + "/lands");
const { STATIC } = await import(path.join(LANDS, "src/game/static-data.mjs"));

const classes = new Map(); // class name -> { fields: Map(name -> csType) }
const isNumArray = (v) => (Array.isArray(v) || ArrayBuffer.isView(v)) && Array.from(v).every((x) => typeof x === "number");
const csName = (k) => k.replace(/s$/, "").replace(/Defs$/, "Def") || k;

function typeOf(v, hint) {
  if (typeof v === "number") return Number.isInteger(v) ? "int" : "double";
  if (typeof v === "string") return "string";
  if (typeof v === "boolean") return "bool";
  if (v === null || v === undefined) return "object";
  if (isNumArray(v)) return Array.from(v).every(Number.isInteger) ? "int[]" : "double[]";
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return "string[]";
  if (Array.isArray(v)) return `${recordClass(v, hint)}[]`;
  return recordClass([v], hint);
}

function recordClass(items, hint) {
  const name = hint;
  if (!classes.has(name)) classes.set(name, new Map());
  const fields = classes.get(name);
  for (const item of items) {
    if (!item || typeof item !== "object") continue;
    for (const [k, v] of Object.entries(item)) if (!fields.has(k) || fields.get(k) === "object") fields.set(k, typeOf(v, `${name}_${k}`));
  }
  return name;
}

function literal(v, type) {
  if (type === "int" || type === "double") return String(v ?? 0);
  if (type === "bool") return v ? "true" : "false";
  if (type === "string") return v == null ? "null" : JSON.stringify(v);
  if (type === "object") return "null";
  if (type.endsWith("[]")) {
    if (v == null) return "null";
    const el = type.slice(0, -2);
    return `new ${type} { ${Array.from(v).map((x) => literal(x, el)).join(", ")} }`;
  }
  // record
  if (v == null) return "null";
  const fields = classes.get(type);
  return `new ${type} { ${[...fields].filter(([k]) => k in v).map(([k, t]) => `${k} = ${literal(v[k], t)}`).join(", ")} }`;
}

const members = [];
for (const [key, value] of Object.entries(STATIC)) {
  const type = typeOf(value, `S_${key}`);
  members.push({ key, type, value });
}
let out = "// GENERATED by tools/gen_static.mjs from src/game/static-data.mjs - do not edit.\n";
out += "// Field names are the JS names, so `this.static.X` in the web build is `@static.X` here.\n";
out += "#pragma warning disable\nnamespace Lol {\n";
for (const [name, fields] of classes) {
  out += `public sealed class ${name} {\n`;
  for (const [k, t] of fields) out += `    public ${t} ${k};\n`;
  out += "}\n";
}
out += "public sealed partial class StaticData {\n";
for (const { key, type, value } of members) out += `    public ${type} ${key} = ${literal(value, type)};\n`;
out += "}\n}\n";
const dest = path.join(path.dirname(new URL(import.meta.url).pathname), "..", "Engine", "Static", "StaticData.g.cs");
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log(`${members.length} tables, ${classes.size} record classes -> ${dest} (${out.length} bytes)`);
